# Data manipulation

This section is mostly about manipulating *tensors*, which are arrays implemented in packages such as tensorflow and pytorch that have the following advantages

* GPU acceleration 
* automatic differentiation. 

In [11]:
# We use pytorch
import torch 

x = torch.arange(12)
print(x)

print(x.shape)

print(x.numel())

# Reshape a tensor without changing the entries 
print(x.reshape(3, 4))


# Typically we initialize tensors with zeros, ones, or random numbers

zeros = torch.zeros((2, 3, 4))
ones = torch.ones((2, 3, 4))
# Standard Gaussian
gauss = torch.randn((2, 3, 4))
print(gauss)

# Explicitly initializing a tensor
array = [[2, 1, 3, 4], [1, 2, 3, 4], [1, 2, 3, 7]]

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[[ 0.1917, -2.1936, -1.4262, -1.0604],
         [ 1.4108, -0.5814, -0.3445, -0.4622],
         [-0.4864,  0.0154, -0.3348, -2.7451]],

        [[ 0.0892, -2.1508, -0.5279,  2.3830],
         [ 1.4597, -0.4515, -0.0296, -0.6917],
         [-3.5650, -0.5821,  2.4661,  0.7200]]])


In [22]:
# Scalar operations lift to tensor operations
x = torch.tensor([1.0, 2, 3, 4, 5])
y = torch.tensor([5, 4, 3, 2, 1])

print(x + y, x - y, x * y, x / y, x ** y)

print(torch.exp(x))

tensor([6., 6., 6., 6., 6.]) tensor([-4., -2.,  0.,  2.,  4.]) tensor([5., 8., 9., 8., 5.]) tensor([0.2000, 0.5000, 1.0000, 2.0000, 5.0000]) tensor([ 1., 16., 27., 16.,  5.])
tensor([  2.7183,   7.3891,  20.0855,  54.5981, 148.4132])


In [29]:
# We can concatenate tensor by providing a list of tensor and an axis
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[0, 3, 2, 4], [4, 7, 6, 8], [8, 11, 10, 12]])

torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 0.,  3.,  2.,  4.],
         [ 4.,  7.,  6.,  8.],
         [ 8., 11., 10., 12.]]),
 tensor([[ 0.,  1.,  2.,  3.,  0.,  3.,  2.,  4.],
         [ 4.,  5.,  6.,  7.,  4.,  7.,  6.,  8.],
         [ 8.,  9., 10., 11.,  8., 11., 10., 12.]]))

In [32]:
# We can compare entries
print(X == Y)

# And sum
(X == Y).sum()

tensor([[ True, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False]])


tensor(6)

In [33]:
# Broadcasting is scary black magic 

a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [38]:
# Indices work like python lists
print(X[-1], X[1:3])

X[1, 2] = 18

print(X)

#We can modify multiple indices
X[0:2, :] = 12
print(X)

tensor([ 8.,  9., 10., 11.]) tensor([[ 4.,  5., 18.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 18.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


Whenever you redefine a variable, it gets put in a new location in memory. This is often undesirable. The alternative is to perform operations *in-place*. 

In [39]:
# New variables are put in a new location in memory 
before = id(Y)
Y = Y + X
id(Y) == before

False

In [41]:
# We use the syntax Y[:] (or Y +=) to perform in-place operations
before = id(Y)
Y[:] = Y + X
id(Y) == before

True

In [42]:
# We can convert to and from NumPy tensors
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [43]:
# We can convert 1d tensors to scalars
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)