# Linear Algebra

In [1]:
import torch

## Scalars, vectors, tensors

In [21]:
# Scalars and 1d tensors are mostly interchangeable
a = torch.tensor([3.0])
b = torch.tensor([2.0])
a

tensor([3.])

In [25]:
# Vectors
x = torch.arange(4, dtype=torch.float32)
x[1], x.shape

(tensor(1.), torch.Size([4]))

In [28]:
# Matrices
A = torch.arange(20).reshape(5, 4)
# Transpose
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [30]:
# Tensors
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## Tensor operations

In [34]:
# Addition, element-wise product, scalar multiplication
A = torch.arange(8, dtype=torch.float32).reshape(2, 2, 2)
B = A.clone()
a = 3
# Note that * is the Hadamard product
A, A + B, A * B, a * A

(tensor([[[0., 1.],
          [2., 3.]],
 
         [[4., 5.],
          [6., 7.]]]),
 tensor([[[ 0.,  2.],
          [ 4.,  6.]],
 
         [[ 8., 10.],
          [12., 14.]]]),
 tensor([[[ 0.,  1.],
          [ 4.,  9.]],
 
         [[16., 25.],
          [36., 49.]]]),
 tensor([[[ 0.,  3.],
          [ 6.,  9.]],
 
         [[12., 15.],
          [18., 21.]]]))

Summing and averaging: 

In [35]:
# Sum all the entries of a tensor
A.sum()

(tensor([[[0., 1.],
          [2., 3.]],
 
         [[4., 5.],
          [6., 7.]]]),
 tensor(28.))

In [40]:
# Or sum along one axis
A.sum(axis=2)

tensor([[ 1.,  5.],
        [ 9., 13.]])

In [41]:
# Or mutliple axes
A.sum(axis=[0, 2])

tensor([10., 18.])

In [44]:
# Means work the same way
A.mean(), A.mean(axis=[0, 2])

(tensor(3.5000), tensor([2.5000, 4.5000]))

Sometimes it's useful to do summing and averaging operations while preserving the number of axes. We do this with the `keepdims=True` parameter. 

In [45]:
A.sum(axis=1, keepdims=True)

tensor([[[ 2.,  4.]],

        [[10., 12.]]])

## Dot Products

In [5]:
# Dot product
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)

torch.dot(x, y)

tensor(6.)

## Matrix-vector multiplication
Using `torch.mv` allows you to pretend that row vectors are column vectors. 

In [7]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)

torch.mv(A, x)

tensor([ 14.,  38.,  62.,  86., 110.])

## Matrix multiplication
We can do matrix multiplication using `torch.mm`. 

In [8]:
B = torch.ones(4, 2)

torch.mm(A, B)

tensor([[ 6.,  6.],
        [22., 22.],
        [38., 38.],
        [54., 54.],
        [70., 70.]])

## Norms

In [11]:
# L_1 norm
torch.abs(x).sum()

tensor(6.)

In [10]:
# L_2 norm
torch.norm(x)

tensor(3.7417)

In [15]:
# Frobenius norm
torch.norm(torch.ones(7, 8))

tensor(7.4833)